"""The curated model catalog (spec section 11) — data-driven, not scattered
across UI components. Estimated VRAM/RAM are engineering estimates, not
measurements — the Benchmark Engine is what produces measured numbers.

The original twelve entries estimate from parameter count (~0.6 bytes/param
for Q4_K_M, plus KV-cache/runtime overhead). Everything added since estimates
from the *actual* GGUF size returned by a HEAD request against the download
URL — weights plus ~600 MB of KV-cache/runtime headroom for VRAM, and a wider
2 GB margin for the CPU-side copy. For a vision model the projector counts
too, since llama-server loads both.

Capabilities are what the app routes on, not decoration: "vision" is what lets
a model be a chat's eyes, "code" and "reasoning" are what the model packs and
the role picker read. See engines/models/packs.py.

Every model_url points to its real Hugging Face repo; license/context-length/
architecture reflect each model's published model card at time of writing.

download_url is a real, verified, direct-download GGUF file URL (HF's CDN,
supports HTTP Range requests for resumability — confirmed via HEAD request,
not assumed). Gated repos (Llama, Gemma need license acceptance + an HF
token to download the original weights) are sourced from bartowski's
ungated community GGUF re-uploads instead — the standard approach local-LLM
tools use, since the quantized artifact itself doesn't carry the gate.

fp16_download_url (optional, "" if absent) is a full-precision GGUF source
for local requantization to a different quant level via llama-quantize
(spec Phase 8). Only set where a real, single-file, ungated source exists
at a practical download size — the official Qwen `*-GGUF` repos, which ship
one `*-fp16.gguf` file per size: Qwen2.5-0.5B (verified end-to-end), plus
Qwen2.5-Coder 1.5B / 3B (same repo layout). Most other curated models
either only ship as multi-GB/split F32 files or require an HF token for the
gated original weights; the Optimize UI shows an honest "quantization
source not available yet" for those rather than a fake button.

mmproj_download_url (optional, "" if absent) is the companion multimodal
projector GGUF for vision models. llama.cpp needs BOTH files to see images:
the LLM plus this vision encoder, passed as --mmproj. A text-only model has
no projector and no flag can give it one, so "" here is what the UI reads to
decide whether image attachments are usable at all. Both URLs below were
HEAD-verified (200, Accept-Ranges: bytes) like the rest of the catalog.
"""
from __future__ import annotations

CURATED_MODELS: list[dict] = [
    {
        "id": "llama-3.1-8b-instruct",
        "name": "Llama 3.1 8B Instruct",
        "family": "Llama",
        "parameter_count": "8B",
        "architecture": "Llama",
        "context_length": 131072,
        "license": "Llama 3.1 Community License",
        "source": "Meta",
        "model_url": "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 7168,
        "est_vram_mb": 5632,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Meta's general-purpose instruction-tuned model with a 128K context window — a strong all-around default for chat and reasoning.",
        "tags": ["general", "chat", "reasoning"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "llama-3.2-3b-instruct",
        "name": "Llama 3.2 3B Instruct",
        "family": "Llama",
        "parameter_count": "3B",
        "architecture": "Llama",
        "context_length": 131072,
        "license": "Llama 3.2 Community License",
        "source": "Meta",
        "model_url": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 3584,
        "est_vram_mb": 2252,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A smaller Llama 3.2 model that keeps the 128K context window — a good fit for mid-range GPUs and fast local iteration.",
        "tags": ["general", "chat", "lightweight"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "llama-3.2-1b-instruct",
        "name": "Llama 3.2 1B Instruct",
        "family": "Llama",
        "parameter_count": "1B",
        "architecture": "Llama",
        "context_length": 131072,
        "license": "Llama 3.2 Community License",
        "source": "Meta",
        "model_url": "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 1536,
        "est_vram_mb": 922,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Meta's smallest Llama 3.2 model — runs comfortably on CPU-only or entry-level GPU potatoes.",
        "tags": ["general", "chat", "tiny", "cpu-friendly"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "mistral-7b-instruct-v0.3",
        "name": "Mistral 7B Instruct v0.3",
        "family": "Mistral",
        "parameter_count": "7B",
        "architecture": "Mistral",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "Mistral AI",
        "model_url": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
        "download_url": "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 6656,
        "est_vram_mb": 4915,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A permissively-licensed, well-rounded 7B model with a long track record as a local-LLM default.",
        "tags": ["general", "chat"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "qwen2.5-7b-instruct",
        "name": "Qwen2.5 7B Instruct",
        "family": "Qwen",
        "parameter_count": "7B",
        "architecture": "Qwen2",
        "context_length": 131072,
        "license": "Apache 2.0",
        "source": "Alibaba Cloud",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-GGUF/resolve/main/Qwen2.5-7B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 6656,
        "est_vram_mb": 4915,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Strong general and coding performance with a 128K context window — one of the best-rounded 7B-class models available.",
        "tags": ["general", "chat", "code"],
        "capabilities": ["chat", "instruct", "code"],
    },
    {
        "id": "qwen2.5-14b-instruct",
        "name": "Qwen2.5 14B Instruct",
        "family": "Qwen",
        "parameter_count": "14B",
        "architecture": "Qwen2",
        "context_length": 131072,
        "license": "Apache 2.0",
        "source": "Alibaba Cloud",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-14B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 11264,
        "est_vram_mb": 9216,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M"],
        "description": "A larger Qwen2.5 for machines with more VRAM to spare — noticeably stronger reasoning at real memory cost.",
        "tags": ["general", "chat", "reasoning"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "qwen2.5-0.5b-instruct",
        "name": "Qwen2.5 0.5B Instruct",
        "family": "Qwen",
        "parameter_count": "0.5B",
        "architecture": "Qwen2",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "Alibaba Cloud",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct",
        "download_url": "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-fp16.gguf",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 1024,
        "est_vram_mb": 512,
        "recommended_quantizations": ["Q4_K_M", "Q8_0", "FP16"],
        "description": "Tiny enough to run on almost anything, including modest laptops — useful for testing the pipeline itself, not heavy-duty chat.",
        "tags": ["tiny", "cpu-friendly", "testing"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "phi-3.5-mini-instruct",
        "name": "Phi-3.5 Mini Instruct",
        "family": "Phi",
        "parameter_count": "3.8B",
        "architecture": "Phi3",
        "context_length": 131072,
        "license": "MIT",
        "source": "Microsoft",
        "model_url": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct",
        "download_url": "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 4096,
        "est_vram_mb": 2662,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Punches well above its 3.8B size on reasoning benchmarks, with an MIT license and a 128K context window.",
        "tags": ["general", "chat", "reasoning", "lightweight"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "gemma-2-9b-it",
        "name": "Gemma 2 9B Instruct",
        "family": "Gemma",
        "parameter_count": "9B",
        "architecture": "Gemma2",
        "context_length": 8192,
        "license": "Gemma Terms of Use",
        "source": "Google",
        "model_url": "https://huggingface.co/google/gemma-2-9b-it",
        "download_url": "https://huggingface.co/bartowski/gemma-2-9b-it-GGUF/resolve/main/gemma-2-9b-it-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 7680,
        "est_vram_mb": 6144,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Google's well-regarded mid-size chat model — a shorter 8K context window in exchange for strong response quality.",
        "tags": ["general", "chat"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "gemma-2-2b-it",
        "name": "Gemma 2 2B Instruct",
        "family": "Gemma",
        "parameter_count": "2B",
        "architecture": "Gemma2",
        "context_length": 8192,
        "license": "Gemma Terms of Use",
        "source": "Google",
        "model_url": "https://huggingface.co/google/gemma-2-2b-it",
        "download_url": "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 2560,
        "est_vram_mb": 1638,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A compact Gemma 2 variant that's easy on VRAM while staying capable for everyday chat.",
        "tags": ["general", "chat", "lightweight"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "deepseek-r1-distill-qwen-7b",
        "name": "DeepSeek-R1-Distill-Qwen-7B",
        "family": "DeepSeek",
        "parameter_count": "7B",
        "architecture": "Qwen2",
        "context_length": 131072,
        "license": "MIT",
        "source": "DeepSeek AI",
        "model_url": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "download_url": "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 6656,
        "est_vram_mb": 4915,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Reasoning-distilled from DeepSeek-R1 onto a Qwen2.5 base — noticeably better at step-by-step problem solving than a typical 7B chat model.",
        "tags": ["reasoning", "chat", "math"],
        "capabilities": ["chat", "reasoning"],
    },
    {
        "id": "tinyllama-1.1b-chat",
        "name": "TinyLlama 1.1B Chat",
        "family": "TinyLlama",
        "parameter_count": "1.1B",
        "architecture": "Llama",
        "context_length": 2048,
        "license": "Apache 2.0",
        "source": "TinyLlama Project",
        "model_url": "https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        "download_url": "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 1536,
        "est_vram_mb": 922,
        "recommended_quantizations": ["Q4_K_M", "Q8_0", "FP16"],
        "description": "About as light as a usable chat model gets — a Serious Potato baseline for the tiniest machines.",
        "tags": ["tiny", "cpu-friendly", "testing"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "smolvlm-500m-instruct",
        "name": "SmolVLM 500M Instruct",
        "family": "SmolVLM",
        "parameter_count": "500M",
        "architecture": "Idefics3",
        "context_length": 8192,
        "license": "Apache 2.0",
        "source": "Hugging Face",
        "model_url": "https://huggingface.co/HuggingFaceTB/SmolVLM-500M-Instruct",
        "download_url": "https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/SmolVLM-500M-Instruct-Q8_0.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/SmolVLM-500M-Instruct-GGUF/resolve/main/mmproj-SmolVLM-500M-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 1536,
        "est_vram_mb": 1024,
        "recommended_quantizations": ["Q8_0"],
        "description": "A genuinely tiny vision-language model — it reads images on a potato. The smallest way to try image attachments in the Playground.",
        "tags": ["vision", "small", "chat"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "gemma-3-4b-it",
        "name": "Gemma 3 4B Instruct",
        "family": "Gemma",
        "parameter_count": "4B",
        "architecture": "Gemma3",
        "context_length": 131072,
        "license": "Gemma Terms of Use",
        "source": "Google",
        "model_url": "https://huggingface.co/google/gemma-3-4b-it",
        "download_url": "https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF/resolve/main/mmproj-model-f16.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 5120,
        "est_vram_mb": 4096,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M"],
        "description": "Google's multimodal Gemma 3 — reads images and holds a 128K context. The capable option when your potato has the headroom.",
        "tags": ["vision", "general", "chat"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "qwen2.5-vl-7b-instruct",
        "name": "Qwen2.5-VL 7B Instruct",
        "family": "Qwen",
        "parameter_count": "7B",
        "architecture": "Qwen2VL",
        "context_length": 128000,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct",
        "download_url": "https://huggingface.co/ggml-org/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/Qwen2.5-VL-7B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/Qwen2.5-VL-7B-Instruct-GGUF/resolve/main/mmproj-Qwen2.5-VL-7B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 7424,
        "est_vram_mb": 5888,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Reads images, screenshots and documents in detail, and is strong enough at text to answer about them on its own.",
        "tags": ["vision", "general", "chat", "documents"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "qwen2.5-vl-3b-instruct",
        "name": "Qwen2.5-VL 3B Instruct",
        "family": "Qwen",
        "parameter_count": "3B",
        "architecture": "Qwen2VL",
        "context_length": 128000,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-VL-3B-Instruct",
        "download_url": "https://huggingface.co/ggml-org/Qwen2.5-VL-3B-Instruct-GGUF/resolve/main/Qwen2.5-VL-3B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/Qwen2.5-VL-3B-Instruct-GGUF/resolve/main/mmproj-Qwen2.5-VL-3B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 4608,
        "est_vram_mb": 3200,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "The same image reading as its 7B sibling at roughly half the memory — the usual pick for a mid-range GPU.",
        "tags": ["vision", "general", "chat", "lightweight"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "qwen2-vl-2b-instruct",
        "name": "Qwen2-VL 2B Instruct",
        "family": "Qwen",
        "parameter_count": "2B",
        "architecture": "Qwen2VL",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct",
        "download_url": "https://huggingface.co/ggml-org/Qwen2-VL-2B-Instruct-GGUF/resolve/main/Qwen2-VL-2B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/Qwen2-VL-2B-Instruct-GGUF/resolve/main/mmproj-Qwen2-VL-2B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 3584,
        "est_vram_mb": 2176,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A small, well-tested vision model. Slower to impress than Qwen2.5-VL, but it fits where that one does not.",
        "tags": ["vision", "chat", "lightweight"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "internvl3-8b-instruct",
        "name": "InternVL3 8B Instruct",
        "family": "InternVL",
        "parameter_count": "8B",
        "architecture": "InternVL",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "OpenGVLab",
        "model_url": "https://huggingface.co/OpenGVLab/InternVL3-8B",
        "download_url": "https://huggingface.co/ggml-org/InternVL3-8B-Instruct-GGUF/resolve/main/InternVL3-8B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/InternVL3-8B-Instruct-GGUF/resolve/main/mmproj-InternVL3-8B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 6912,
        "est_vram_mb": 5376,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Strong on charts, diagrams and dense document pages, with an unusually small vision encoder for its size.",
        "tags": ["vision", "general", "chat", "documents"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "internvl3-2b-instruct",
        "name": "InternVL3 2B Instruct",
        "family": "InternVL",
        "parameter_count": "2B",
        "architecture": "InternVL",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "OpenGVLab",
        "model_url": "https://huggingface.co/OpenGVLab/InternVL3-2B",
        "download_url": "https://huggingface.co/ggml-org/InternVL3-2B-Instruct-GGUF/resolve/main/InternVL3-2B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/InternVL3-2B-Instruct-GGUF/resolve/main/mmproj-InternVL3-2B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 3328,
        "est_vram_mb": 2048,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Document and chart reading on a small budget — the cheapest way to give a text-only setup a pair of eyes.",
        "tags": ["vision", "chat", "lightweight", "documents"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "smolvlm2-2.2b-instruct",
        "name": "SmolVLM2 2.2B Instruct",
        "family": "SmolVLM",
        "parameter_count": "2.2B",
        "architecture": "Idefics3",
        "context_length": 8192,
        "license": "Apache 2.0",
        "source": "Hugging Face",
        "model_url": "https://huggingface.co/HuggingFaceTB/SmolVLM2-2.2B-Instruct",
        "download_url": "https://huggingface.co/ggml-org/SmolVLM2-2.2B-Instruct-GGUF/resolve/main/SmolVLM2-2.2B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/SmolVLM2-2.2B-Instruct-GGUF/resolve/main/mmproj-SmolVLM2-2.2B-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 3584,
        "est_vram_mb": 2176,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Hugging Face's compact vision model, tuned for describing images and short video frames on modest hardware.",
        "tags": ["vision", "chat", "lightweight"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "smolvlm-256m-instruct",
        "name": "SmolVLM 256M Instruct",
        "family": "SmolVLM",
        "parameter_count": "256M",
        "architecture": "Idefics3",
        "context_length": 8192,
        "license": "Apache 2.0",
        "source": "Hugging Face",
        "model_url": "https://huggingface.co/HuggingFaceTB/SmolVLM-256M-Instruct",
        "download_url": "https://huggingface.co/ggml-org/SmolVLM-256M-Instruct-GGUF/resolve/main/SmolVLM-256M-Instruct-Q8_0.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/SmolVLM-256M-Instruct-GGUF/resolve/main/mmproj-SmolVLM-256M-Instruct-Q8_0.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 2304,
        "est_vram_mb": 896,
        "recommended_quantizations": ["Q8_0"],
        "description": "The smallest model here that can see. Captions and simple questions only, but it runs on almost anything.",
        "tags": ["vision", "tiny", "cpu-friendly"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "gemma-3-12b-it",
        "name": "Gemma 3 12B Instruct",
        "family": "Gemma",
        "parameter_count": "12B",
        "architecture": "Gemma3",
        "context_length": 131072,
        "license": "Gemma Terms of Use",
        "source": "Google",
        "model_url": "https://huggingface.co/google/gemma-3-12b-it",
        "download_url": "https://huggingface.co/ggml-org/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/ggml-org/gemma-3-12b-it-GGUF/resolve/main/mmproj-model-f16.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 9728,
        "est_vram_mb": 8320,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "The big Gemma 3: reads images, holds 128K of context, and writes well enough to be the only model you load.",
        "tags": ["vision", "general", "chat", "large"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "minicpm-v-2.6",
        "name": "MiniCPM-V 2.6",
        "family": "MiniCPM",
        "parameter_count": "8B",
        "architecture": "Qwen2",
        "context_length": 32768,
        "license": "Apache 2.0 (model), MiniCPM Model License",
        "source": "OpenBMB",
        "model_url": "https://huggingface.co/openbmb/MiniCPM-V-2_6",
        "download_url": "https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/resolve/main/ggml-model-Q4_K_M.gguf",
        "mmproj_download_url": "https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/resolve/main/mmproj-model-f16.gguf",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": False,
        "est_ram_mb": 7424,
        "est_vram_mb": 6016,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Built for OCR and dense text in images — the one to reach for when the picture is mostly words.",
        "tags": ["vision", "chat", "ocr", "documents"],
        "capabilities": ["chat", "instruct", "vision"],
    },
    {
        "id": "qwen2.5-coder-7b-instruct",
        "name": "Qwen2.5-Coder 7B Instruct",
        "family": "Qwen",
        "parameter_count": "7B",
        "architecture": "Qwen2",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-7B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 6400,
        "est_vram_mb": 5120,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A code specialist that holds its own against much larger general models on writing, explaining and fixing code.",
        "tags": ["code", "chat"],
        "capabilities": ["chat", "instruct", "code"],
    },
    {
        "id": "qwen2.5-coder-3b-instruct",
        "name": "Qwen2.5-Coder 3B Instruct",
        "family": "Qwen",
        "parameter_count": "3B",
        "architecture": "Qwen2",
        "context_length": 32768,
        "license": "Qwen Research License",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-Coder-3B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Qwen2.5-Coder-3B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-3B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        # Official Qwen GGUF repo, single-file fp16 — same repo layout as the
        # verified Qwen2.5-0.5B source above.
        "fp16_download_url": "https://huggingface.co/Qwen/Qwen2.5-Coder-3B-Instruct-GGUF/resolve/main/qwen2.5-coder-3b-instruct-fp16.gguf",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 3840,
        "est_vram_mb": 2432,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0", "FP16"],
        "description": "Most of the 7B coder's usefulness at a third of the memory — a practical everyday coding companion.",
        "tags": ["code", "chat", "lightweight"],
        "capabilities": ["chat", "instruct", "code"],
    },
    {
        "id": "qwen2.5-coder-1.5b-instruct",
        "name": "Qwen2.5-Coder 1.5B Instruct",
        "family": "Qwen",
        "parameter_count": "1.5B",
        "architecture": "Qwen2",
        "context_length": 32768,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct",
        "download_url": "https://huggingface.co/bartowski/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-1.5B-Instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        # Official Qwen GGUF repo, single-file fp16 — same repo layout as the
        # verified Qwen2.5-0.5B source above.
        "fp16_download_url": "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-fp16.gguf",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 3072,
        "est_vram_mb": 1536,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0", "FP16"],
        "description": "Small enough to run alongside another model, and still better at code than a general model its size.",
        "tags": ["code", "tiny", "cpu-friendly"],
        "capabilities": ["chat", "instruct", "code"],
    },
    {
        "id": "deepseek-r1-distill-llama-8b",
        "name": "DeepSeek-R1 Distill Llama 8B",
        "family": "DeepSeek",
        "parameter_count": "8B",
        "architecture": "Llama",
        "context_length": 131072,
        "license": "MIT",
        "source": "DeepSeek",
        "model_url": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
        "download_url": "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 6656,
        "est_vram_mb": 5248,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Thinks step by step before answering. Slower per reply, but far better on maths and multi-step problems.",
        "tags": ["reasoning", "chat", "math"],
        "capabilities": ["chat", "reasoning"],
    },
    {
        "id": "deepseek-r1-distill-qwen-1.5b",
        "name": "DeepSeek-R1 Distill Qwen 1.5B",
        "family": "DeepSeek",
        "parameter_count": "1.5B",
        "architecture": "Qwen2",
        "context_length": 131072,
        "license": "MIT",
        "source": "DeepSeek",
        "model_url": "https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
        "download_url": "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 3072,
        "est_vram_mb": 1664,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Step-by-step reasoning small enough for a CPU-only potato. Surprisingly good at maths for its size.",
        "tags": ["reasoning", "tiny", "math", "cpu-friendly"],
        "capabilities": ["chat", "reasoning"],
    },
    {
        "id": "qwen3-4b",
        "name": "Qwen3 4B",
        "family": "Qwen",
        "parameter_count": "4B",
        "architecture": "Qwen3",
        "context_length": 40960,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen3-4B",
        "download_url": "https://huggingface.co/ggml-org/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 4352,
        "est_vram_mb": 2944,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A recent all-rounder that can switch into a longer thinking mode when a question needs it.",
        "tags": ["general", "chat", "reasoning"],
        "capabilities": ["chat", "instruct", "reasoning"],
    },
    {
        "id": "qwen3-1.7b",
        "name": "Qwen3 1.7B",
        "family": "Qwen",
        "parameter_count": "1.7B",
        "architecture": "Qwen3",
        "context_length": 40960,
        "license": "Apache 2.0",
        "source": "Alibaba",
        "model_url": "https://huggingface.co/Qwen/Qwen3-1.7B",
        "download_url": "https://huggingface.co/ggml-org/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 3328,
        "est_vram_mb": 1792,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Small, current and quick — a better default than the older tiny models when you just need fast answers.",
        "tags": ["general", "chat", "tiny", "cpu-friendly"],
        "capabilities": ["chat", "instruct"],
    },
    {
        "id": "phi-4-mini-instruct",
        "name": "Phi-4 Mini Instruct",
        "family": "Phi",
        "parameter_count": "3.8B",
        "architecture": "Phi3",
        "context_length": 131072,
        "license": "MIT",
        "source": "Microsoft",
        "model_url": "https://huggingface.co/microsoft/Phi-4-mini-instruct",
        "download_url": "https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 4352,
        "est_vram_mb": 2944,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "Microsoft's small model trained heavily on reasoning and instruction data, with a 128K context window.",
        "tags": ["general", "chat", "reasoning"],
        "capabilities": ["chat", "instruct", "reasoning"],
    },
    {
        "id": "mistral-nemo-instruct-2407",
        "name": "Mistral Nemo 12B Instruct",
        "family": "Mistral",
        "parameter_count": "12B",
        "architecture": "Mistral",
        "context_length": 131072,
        "license": "Apache 2.0",
        "source": "Mistral AI",
        "model_url": "https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407",
        "download_url": "https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf",
        "mmproj_download_url": "",
        "fp16_download_url": "",
        "supported_backends": ["llama.cpp"],
        "supported_quant_formats": ["GGUF"],
        "finetune_support": True,
        "est_ram_mb": 9216,
        "est_vram_mb": 7680,
        "recommended_quantizations": ["Q4_K_M", "Q5_K_M", "Q8_0"],
        "description": "A 12B built with NVIDIA, strong on multilingual chat and long documents when you have the memory for it.",
        "tags": ["general", "chat", "multilingual", "large"],
        "capabilities": ["chat", "instruct"],
    },
]
