"""add fp16 source url and download variant

Revision ID: 1083fbe1178c
Revises: 939a8ee73ab3
Create Date: 2026-08-23 22:19:22.537620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1083fbe1178c'
down_revision: Union[str, None] = '939a8ee73ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this doesn't fail against a DB that already has rows
    # (see the download_url migration's note — same reasoning here).
    op.add_column('download_jobs', sa.Column('variant', sa.String(), nullable=False, server_default='quantized'))
    op.add_column('models', sa.Column('fp16_download_url', sa.String(), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'fp16_download_url')
    op.drop_column('download_jobs', 'variant')
    # ### end Alembic commands ###
