"""initial schema

Revision ID: 4101e507f293
Revises: 
Create Date: 2026-08-23 14:57:24.009784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4101e507f293'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('example_count', sa.Integer(), nullable=True),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('avg_tokens', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('duplicate_pct', sa.Float(), nullable=True),
    sa.Column('valid_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hardware_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('os_name', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=False),
    sa.Column('cpu_model', sa.String(), nullable=False),
    sa.Column('cpu_vendor', sa.String(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_threads', sa.Integer(), nullable=True),
    sa.Column('cpu_architecture', sa.String(), nullable=False),
    sa.Column('cpu_instruction_sets', sa.JSON(), nullable=False),
    sa.Column('gpu_vendor', sa.String(), nullable=False),
    sa.Column('gpu_model', sa.String(), nullable=False),
    sa.Column('gpu_vram_mb', sa.Integer(), nullable=True),
    sa.Column('gpu_driver_version', sa.String(), nullable=False),
    sa.Column('gpu_utilization_pct', sa.Float(), nullable=True),
    sa.Column('gpu_temp_c', sa.Float(), nullable=True),
    sa.Column('compute_backend', sa.String(), nullable=False),
    sa.Column('ram_total_mb', sa.Integer(), nullable=True),
    sa.Column('ram_available_mb', sa.Integer(), nullable=True),
    sa.Column('storage_total_gb', sa.Float(), nullable=True),
    sa.Column('storage_available_gb', sa.Float(), nullable=True),
    sa.Column('potato_score', sa.Integer(), nullable=True),
    sa.Column('potato_classification', sa.String(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('raw_detection_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('input_artifact', sa.String(), nullable=True),
    sa.Column('output_artifact', sa.String(), nullable=True),
    sa.Column('logs_path', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('parameter_count', sa.String(), nullable=False),
    sa.Column('architecture', sa.String(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('model_url', sa.String(), nullable=False),
    sa.Column('supported_backends', sa.JSON(), nullable=False),
    sa.Column('supported_quant_formats', sa.JSON(), nullable=False),
    sa.Column('finetune_support', sa.Boolean(), nullable=False),
    sa.Column('est_ram_mb', sa.Integer(), nullable=False),
    sa.Column('est_vram_mb', sa.Integer(), nullable=False),
    sa.Column('recommended_quantizations', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_model_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('quantization', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_model_id', sa.String(), nullable=False),
    sa.Column('model_artifact_id', sa.String(), nullable=False),
    sa.Column('adapter_id', sa.String(), nullable=True),
    sa.Column('backend', sa.String(), nullable=False),
    sa.Column('gpu_offload_layers', sa.Integer(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapters.id'], ),
    sa.ForeignKeyConstraint(['base_model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['model_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantization_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('source_artifact_id', sa.String(), nullable=True),
    sa.Column('target_format', sa.String(), nullable=False),
    sa.Column('target_quant', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('output_artifact_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['model_artifacts.id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('training_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('base_model_id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('total_epochs', sa.Integer(), nullable=True),
    sa.Column('current_loss', sa.Float(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('output_adapter_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['base_model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['output_adapter_id'], ['adapters.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=True),
    sa.Column('tokens_per_sec', sa.Float(), nullable=True),
    sa.Column('prompt_tokens_per_sec', sa.Float(), nullable=True),
    sa.Column('ttft_seconds', sa.Float(), nullable=True),
    sa.Column('total_latency_seconds', sa.Float(), nullable=True),
    sa.Column('cpu_util_pct', sa.Float(), nullable=True),
    sa.Column('gpu_util_pct', sa.Float(), nullable=True),
    sa.Column('vram_mb', sa.Float(), nullable=True),
    sa.Column('ram_mb', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('gpu_offload_layers', sa.Integer(), nullable=True),
    sa.Column('generation_params_json', sa.JSON(), nullable=False),
    sa.Column('is_measured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('build_id', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('build_id', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('tokens_per_sec', sa.Float(), nullable=True),
    sa.Column('ttft_seconds', sa.Float(), nullable=True),
    sa.Column('cpu_util_pct', sa.Float(), nullable=True),
    sa.Column('gpu_util_pct', sa.Float(), nullable=True),
    sa.Column('vram_mb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['inference_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_records')
    op.drop_table('inference_sessions')
    op.drop_table('benchmarks')
    op.drop_table('training_jobs')
    op.drop_table('quantization_jobs')
    op.drop_table('builds')
    op.drop_table('model_artifacts')
    op.drop_table('adapters')
    op.drop_table('models')
    op.drop_table('jobs')
    op.drop_table('hardware_profiles')
    op.drop_table('datasets')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
