"""add download_url and download_jobs

Revision ID: b7c6076896f4
Revises: 4101e507f293
Create Date: 2026-08-23 20:52:34.172759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7c6076896f4'
down_revision: Union[str, None] = '4101e507f293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('bytes_downloaded', sa.Integer(), nullable=False),
    sa.Column('bytes_total', sa.Integer(), nullable=True),
    sa.Column('speed_bps', sa.Float(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('resumed_count', sa.Integer(), nullable=False),
    sa.Column('output_artifact_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # server_default='' so this doesn't fail against a DB that already has
    # seeded model rows (NOT NULL ADD COLUMN needs a default for them);
    # seed_models() overwrites-on-conflict is a no-op for existing rows
    # though, so this is really only relevant to *new* rows this migration
    # runs against before any dev's next seed pass corrects stale ones.
    op.add_column('models', sa.Column('download_url', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'download_url')
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
